# sensitibot.toml

[build-system]
requires = [
    "setuptools>=64.0.0",
    "wheel",
    "requests==2.28.2",
    "python-dotenv==1.0.0",
    "pandas==1.5.3"
    ]
build-backend = "setuptools.build_meta"

[project]
name = "SensitiBot"
version = "0.0.1"
description = "My awesome Hello CLI application"
readme = "README.md"
authors = [{name="José Manuel Martín Luque", email="martinluquejm@gmail.com" }]

[project.scripts]
sensitibot = "sensitibot.sensitibot:main"

[tool.setuptools]
packages = ["sensitibot", "local", "github", "reader"]

[project.urls]
"Homepage" = "https://github.com/TFG-SensitiBot/SensitiBot"
"Bug Tracker" = "https://github.com/TFG-SensitiBot/SensitiBot/issues"
